<?php

require_once __DIR__ . '/../../src/Controller/AbstractAdminController.php';

class AdminDPDBalticsModuleController extends ModuleAdminController
{
    public function postProcess()
    {
        Tools::redirectAdmin($this->context->link->getAdminLink(DPDBaltics::ADMIN_SETTINGS_CONTROLLER));
        return parent::postProcess(); // TODO: Change the autogenerated stub
    }
}
