services:
  Invertus\dpdBaltics\Provider\ImportExportOptionsProvider:
    arguments:
      - '@dpdbaltics'

  Invertus\dpdBaltics\Provider\ImportExportURLProvider:
    arguments:
      - '@context'

  Invertus\dpdBaltics\Provider\ProductShippingCostProvider:
    arguments:
      - '@dpdbaltics'
      -  '@Invertus\dpdBaltics\Repository\ProductRepository'
      -  '@Invertus\dpdBaltics\Repository\ZoneRepository'
      -  '@Invertus\dpdBaltics\Repository\PriceRuleRepository'
      -  '@currency'

  Invertus\dpdBaltics\Provider\ZoneRangeProvider:
    arguments:
      - '@language'
      - '@Invertus\dpdBaltics\Repository\ZoneRangeRepository'

  Invertus\dpdBaltics\Provider\ProductAvailabilityProvider:
    arguments:
      - '@language'
      - '@Invertus\dpdBaltics\Repository\ProductAvailabilityRepository'

  Invertus\dpdBaltics\Provider\CurrentCountryProvider:
    arguments:
      - '@context'
